# Generated by Django 5.1.7 on 2025-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordServerConfigModel",
            fields=[
                ("server_id", models.IntegerField()),
                (
                    "default_voice_model_type",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("default_voice_model_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "discord_server_config_model",
                "managed": True,
            },
        ),
    ]
