# Generated by Django 4.2 on 2025-03-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discordserverconfigmodel",
            old_name="default_voice_model_id",
            new_name="default_voice_model_key",
        ),
        migrations.RemoveField(
            model_name="discordserverconfigmodel",
            name="default_voice_model_type",
        ),
        migrations.AlterField(
            model_name="discordserverconfigmodel",
            name="server_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
